export const REGIONS = [
  {
    id: 'tashkent_city',
    name: 'Toshkent shahri',
    nameRu: 'Город Ташкент',
    cities:   ['Toshkent'],
    citiesRu: ['Ташкент'],
  },
  {
    id: 'tashkent',
    name: 'Toshkent viloyati',
    nameRu: 'Ташкентская область',
    cities:   ['Nurafshon', 'Angren', 'Bekobod', 'Chirchiq', 'Ohangaron', 'Olmaliq', "Yangiyo'l", "Bo'stonliq", 'Qibray'],
    citiesRu: ['Нурафшон', 'Ангрен', 'Бекабад', 'Чирчик', 'Ахангаран', 'Алмалык', 'Янгиюль', 'Бостанлык', 'Кибрай'],
  },
  {
    id: 'andijan',
    name: 'Andijon viloyati',
    nameRu: 'Андижанская область',
    cities:   ['Andijon', 'Asaka', 'Xonobod', 'Shahrixon', 'Paxtaobod', 'Marhamat', 'Baliqchi', 'Buloqboshi', 'Jalaquduq', "Qo'rg'ontepa"],
    citiesRu: ['Андижан', 'Асака', 'Хонобод', 'Шахрихон', 'Пахтаобод', 'Мархамат', 'Балыкчи', 'Булакбаши', 'Джалакудук', 'Кургантепа'],
  },
  {
    id: 'fergana',
    name: "Farg'ona viloyati",
    nameRu: 'Ферганская область',
    cities:   ["Farg'ona", "Marg'ilon", "Qo'qon", 'Quvasoy', 'Rishton', 'Beshariq', "Dang'ara", 'Oltiariq', 'Toshloq'],
    citiesRu: ['Фергана', 'Маргилан', 'Коканд', 'Кувасай', 'Риштан', 'Бешарык', 'Дангара', 'Алтыарык', 'Ташлак'],
  },
  {
    id: 'namangan',
    name: 'Namangan viloyati',
    nameRu: 'Наманганская область',
    cities:   ['Namangan', 'Chortoq', 'Chust', 'Kosonsoy', 'Mingbuloq', 'Norin', 'Pop', "To'raqo'rg'on", "Uchqo'rg'on"],
    citiesRu: ['Наманган', 'Чартак', 'Чуст', 'Касансай', 'Мингбулак', 'Нарын', 'Поп', 'Туракурган', 'Учкурган'],
  },
  {
    id: 'samarkand',
    name: 'Samarqand viloyati',
    nameRu: 'Самаркандская область',
    cities:   ['Samarqand', "Kattaqo'rg'on", 'Ishtixon', 'Jomboy', 'Urgut', 'Payariq', "Pastdarg'om", 'Oqdaryo'],
    citiesRu: ['Самарканд', 'Каттакурган', 'Иштыхан', 'Джомбой', 'Ургут', 'Пайарык', 'Пастдаргом', 'Акдарья'],
  },
  {
    id: 'bukhara',
    name: 'Buxoro viloyati',
    nameRu: 'Бухарская область',
    cities:   ['Buxoro', "G'ijduvon", 'Kogon', 'Olot', 'Romitan', 'Shofirkon', 'Vobkent'],
    citiesRu: ['Бухара', 'Гиждуван', 'Каган', 'Олот', 'Ромитан', 'Шафиркан', 'Вабкент'],
  },
  {
    id: 'khorezm',
    name: 'Xorazm viloyati',
    nameRu: 'Хорезмская область',
    cities:   ['Urganch', 'Xiva', "Bog'ot", 'Gurlan', 'Hazorasp', "Qo'shko'pir", 'Shovat'],
    citiesRu: ['Ургенч', 'Хива', 'Богот', 'Гурлен', 'Хазарасп', 'Кошкупыр', 'Шават'],
  },
  {
    id: 'kashkadarya',
    name: 'Qashqadaryo viloyati',
    nameRu: 'Кашкадарьинская область',
    cities:   ['Qarshi', "G'uzor", 'Kitob', 'Koson', 'Shahrisabz', "Yakkabog'", 'Muborak'],
    citiesRu: ['Карши', 'Гузар', 'Китаб', 'Косон', 'Шахрисабз', 'Яккабаг', 'Мубарек'],
  },
  {
    id: 'surkhandarya',
    name: 'Surxondaryo viloyati',
    nameRu: 'Сурхандарьинская область',
    cities:   ['Termiz', 'Denov', "Jarqo'rg'on", 'Sherobod', 'Boysun', 'Oltinsoy'],
    citiesRu: ['Термез', 'Денау', 'Джаркурган', 'Шерабад', 'Байсун', 'Алтынсай'],
  },
  {
    id: 'jizzakh',
    name: 'Jizzax viloyati',
    nameRu: 'Джизакская область',
    cities:   ['Jizzax', "Do'stlik", "G'allaorol", 'Paxtakor', 'Zomin', 'Zafarobod'],
    citiesRu: ['Джизак', 'Дустлик', 'Галлаорал', 'Пахтакор', 'Зомин', 'Зафаробод'],
  },
  {
    id: 'syrdarya',
    name: 'Sirdaryo viloyati',
    nameRu: 'Сырдарьинская область',
    cities:   ['Guliston', 'Boyovut', 'Sardoba', 'Shirin', 'Xovos'],
    citiesRu: ['Гулистан', 'Баяут', 'Сардоба', 'Ширин', 'Ховос'],
  },
  {
    id: 'navoi',
    name: 'Navoiy viloyati',
    nameRu: 'Навоийская область',
    cities:   ['Navoiy', 'Karmana', 'Nurota', 'Zarafshon', 'Uchquduq'],
    citiesRu: ['Навои', 'Кармана', 'Нурата', 'Зарафшан', 'Учкудук'],
  },
  {
    id: 'karakalpakstan',
    name: "Qoraqalpog'iston",
    nameRu: 'Каракалпакстан',
    cities:   ['Nukus', 'Beruniy', 'Chimboy', "Xo'jayli", "Qo'ng'irot", "To'rtko'l"],
    citiesRu: ['Нукус', 'Беруни', 'Чимбай', 'Ходжейли', 'Кунград', 'Турткуль'],
  },
];
